---
- name: Install Ruby (Ubuntu)
  hosts: all
  tasks:
     - name: apt update
       command: "sudo apt update"
     - name: install postgresql
       command: "sudo apt install -y postgresql libpq-dev"
     - name: install git
       command: "sudo apt install -y git"
     - name: install packages to build ruby
       command: "sudo apt install -y build-essential libssl-dev libreadline-dev zlib1g-dev"
     - name: install rbenv
       command: "git clone https://github.com/sstephenson/rbenv.git ~/.rbenv"
     - name: setup environment variables (copy .bashrc)
       copy:
         src: bashrc
         dest: "{{ ansible_facts.env.HOME }}/.bashrc"
     - name: Create a directory
       file:
         path: "{{ ansible_facts.env.HOME }}/.rbenv/plugins"
         state: directory
         recurse: yes
     - name: install ruby-build
       command: "git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build"
     - name: install ruby
       command: ~/.rbenv/rbenv install 3.0.3"
