---
- name: Install Dependencies (Ubuntu)
  hosts: all
  tasks:
    - name: install dependency
      apt:
        pkg:
          - postgresql
          - libpq-dev
          - git
          - build-essential
          - libssl-dev
          - libreadline-dev
          - zlib1g-dev
          - nginx
        update_cache: yes
      become: true
